function generate_matlab_reference(adcs_dir, out_file)
% GENERATE_MATLAB_REFERENCE  Run the team's MATLAB ADCS code on fixed inputs and write the
% inputs + MATLAB outputs to a C header, which src/test.c (suite "MATLAB parity") replays
% through the C port.
%
%   generate_matlab_reference                      % defaults below
%   generate_matlab_reference(adcs_dir, out_file)
%
% adcs_dir defaults to ../adcs next to this repo; out_file to include/matlab_reference.h.
% Headless:  tools/matlab/run_matlab_parity.sh
%
% Nothing in ../adcs is modified. Where the MATLAB code has a known bug, the offending file is
% copied to a temp dir with a single, exact text replacement ("fixed" variant) so the C code can
% be compared against both the raw MATLAB and the MATLAB-with-that-fix. If a replacement no
% longer matches (i.e. the MATLAB was changed upstream) the fixed variant falls back to the raw
% file and the header records that, so the C tests can say so.

here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(here));
if nargin < 1 || isempty(adcs_dir)
    adcs_dir = fullfile(fileparts(repo), 'adcs');
end
if nargin < 2 || isempty(out_file)
    out_file = fullfile(repo, 'include', 'matlab_reference.h');
end
alg = fullfile(adcs_dir, 'MATLAB', 'Algorithms');
assert(isfolder(alg), 'MATLAB algorithms not found at %s', alg);

tmp = tempname;
mkdir(tmp);
old_path = path;
cleanup = onCleanup(@() restore(old_path, tmp));

addpath(alg);
% Aerospace/Robotics toolbox functions used by pointing_error.m, only if not installed
shim_names = {'quatmultiply', 'quatinv', 'rotm2quat'};
used_shims = {};
for i = 1:numel(shim_names)
    if exist(shim_names{i}) == 0 %#ok<EXIST>
        used_shims{end+1} = shim_names{i}; %#ok<AGROW>
    end
end
if ~isempty(used_shims)
    shim_dir = fullfile(tmp, 'shims');
    mkdir(shim_dir);
    for i = 1:numel(used_shims)
        copyfile(fullfile(here, 'shims', [used_shims{i} '.m']), shim_dir);
    end
    addpath(shim_dir);
end

% Dispatchers give access to local functions: ref_X('name', args...) == name(args...) inside X.m
make_dispatcher(alg, 'magnetosphere.m', tmp, 'ref_magnetosphere', {});
make_dispatcher(alg, 'simulink.m', tmp, 'ref_simulink', {});
make_dispatcher(alg, 'eceftoeci.m', tmp, 'ref_eceftoeci', {});
wmm_fixes = {
    'B_ecef = R_ned2ecef * [B_north; B_east; B_down];', ...
    'B_ecef = R_ned2ecef'' * [B_north; B_east; B_down];';   % matrix is ECEF->NED, need its transpose
    'B_N = -B_X_geo * cos(psi) - B_Z_geo * sin(psi);', ...
    'B_N = -B_X_geo * cos(psi) + B_Z_geo * sin(psi);'};     % geodetic rotation sign
wmm_fixed_ok = make_dispatcher(alg, 'magnetosphere.m', tmp, 'ref_magnetosphere_fixed', wmm_fixes);
m2c_fixes = {'    r = [1 1 1];', sprintf('    r = [1 1 1];\n    mu_r = [1 1 1];')}; % mu_r is never defined
m2c_fixed_ok = make_dispatcher(alg, 'moment2current3axis.m', tmp, 'ref_moment2current_fixed', m2c_fixes);
% "Two Body Propogation.m" mixes a function with script code (and has a space in its name), so
% pull the function out into its own file
extract_function(fullfile(alg, 'Two Body Propogation.m'), 'propogateOrbitalElements', ...
                 'new_true_anomaly = rad2deg(new_true_anomaly);', tmp);
addpath(tmp);
rehash;

% Written to a temp file and moved into place only if everything succeeds
tmp_out = fullfile(tmp, 'matlab_reference.h');
fid = fopen(tmp_out, 'w');
assert(fid > 0, 'cannot write %s', tmp_out);
fprintf(fid, '// GENERATED by tools/matlab/generate_matlab_reference.m -- do not edit by hand.\n');
[git_status, adcs_rev] = system(sprintf('git -C "%s" rev-parse --short HEAD', adcs_dir));
if git_status ~= 0, adcs_rev = 'unknown'; end
[~, dirty] = system(sprintf('git -C "%s" status --porcelain -- MATLAB/Algorithms', adcs_dir));
if ~isempty(strtrim(dirty)), adcs_rev = [strtrim(adcs_rev) '+local-changes']; end
fprintf(fid, '// MATLAB %s, adcs repo MATLAB/Algorithms at commit %s\n', version, strtrim(adcs_rev));
fprintf(fid, '// Regenerate with tools/matlab/run_matlab_parity.sh\n');
fprintf(fid, '#ifndef MATLAB_REFERENCE_H\n#define MATLAB_REFERENCE_H\n\n');
fprintf(fid, '#define ML_REFERENCE_AVAILABLE 1\n');
fprintf(fid, '#define ML_USED_SHIMS "%s"\n', strjoin(used_shims, ','));
fprintf(fid, '#define ML_WMM_FIXES_APPLIED %d\n', wmm_fixed_ok);
fprintf(fid, '#define ML_M2C_FIX_APPLIED %d\n\n', m2c_fixed_ok);

rng(20260923, 'twister');

%% ---------------- Quaternion.m ----------------
N = 60;
in = zeros(N, 14);
out = zeros(N, 25);
for k = 1:N
    q1 = randn(1, 4);
    if k > N / 2
        q1 = q1 / norm(q1);              % half unit, half non-unit
    end
    q2 = randn(1, 4);
    v = 5 * randn(1, 3);
    ang = pi * rand;
    if k <= 5, ang = 10^(-k - 1); end    % small angles
    if k > 5 && k <= 8, ang = pi - 10^(-k + 4); end % close to pi
    ax = randn(1, 3); ax = ax / norm(ax);
    rv = ang * ax;
    Q1 = Quaternion(q1); Q2 = Quaternion(q2);
    qn1 = Q1.quaternion_normalize();
    in(k, :) = [q1, q2, v, rv];
    out(k, :) = [Q1.quaternion_multiply(Q2).to_array(), ...
                 qn1.to_array(), ...
                 Q1.quaternion_inverse().to_array(), ...
                 Q1.apply_rotation(v), ...
                 qn1.quaternion2rotation_vec(), ...
                 Quaternion.rotation_vec2quaternion(rv).to_array(), ...
                 Quaternion.quat_diff(qn1, Q2.quaternion_normalize())];
end
comment(fid, 'Quaternion.m. in: q1(4) q2(4) v(3) rv(3). out: q1*q2(4) norm(q1)(4) inv(q1)(4) apply(q1,v)(3) rotvec(norm q1)(3) rv2quat(rv)(4) quat_diff(norm q1, norm q2)(3)');
emit(fid, 'ML_QUAT_IN', in);
emit(fid, 'ML_QUAT_OUT', out);

%% ---------------- bDot.m ----------------
N = 20;
in = zeros(N, 8); out = zeros(N, 3);
for k = 1:N
    Mt = 5e-5 * randn(1, 3); Mt1 = Mt + 1e-6 * randn(1, 3);
    kk = 10^(4 * rand - 1); dT = 0.05 + rand;
    [mx, my, mz] = bDot(Mt(:), Mt1(:), kk, dT);
    in(k, :) = [Mt, Mt1, kk, dT];
    out(k, :) = [mx, my, mz];
end
comment(fid, 'bDot.m. in: M_t(3) M_t_minus_1(3) k dT. out: dipole(3)');
emit(fid, 'ML_BDOT_IN', in);
emit(fid, 'ML_BDOT_OUT', out);

%% ---------------- PD_loop.m ----------------
N = 30;
in = zeros(N, 7); out = zeros(N, 3);
for k = 1:N
    q = randn(1, 4); q = q / norm(q);
    if k <= 3, q = [1 0 0 0]; end
    omega_deg = 5 * randn(1, 3);
    if k == 2, omega_deg = [0 0 0]; end
    if k >= N - 2, omega_deg = 1e5 * randn(1, 3); end % saturation
    tau = PD_loop(omega_deg(:), q(:));
    in(k, :) = [omega_deg, q];
    out(k, :) = tau(:)';
end
comment(fid, 'PD_loop.m. in: omega (DEG/s)(3) q_error(4). out: tau(3)');
emit(fid, 'ML_PD_IN', in);
emit(fid, 'ML_PD_OUT', out);

%% ---------------- torque2moment3axis.m ----------------
N = 30;
in = zeros(N, 6); out = zeros(N, 3);
for k = 1:N
    tau = 1e-6 * randn(1, 3); B = 4e-5 * randn(1, 3);
    m = torque2moment3axis(tau(:), B(:));
    in(k, :) = [tau, B];
    out(k, :) = m(:)';
end
comment(fid, 'torque2moment3axis.m. in: tau(3) B(3). out: m(3)');
emit(fid, 'ML_T2M_IN', in);
emit(fid, 'ML_T2M_OUT', out);

%% ---------------- moment2current3axis.m ----------------
try
    moment2current3axis([1; 2; 3], [1; 1; 1]);
    raw_err = '';
catch e
    raw_err = e.message;
end
fprintf(fid, '// moment2current3axis.m as written: %s\n', ternary(isempty(raw_err), 'runs', 'ERRORS'));
fprintf(fid, '#define ML_M2C_RAW_ERROR "%s"\n\n', strrep(raw_err, '"', ''''));
N = 20;
in = zeros(N, 6); out = zeros(N, 3);
for k = 1:N
    m = 2 * randn(1, 3);
    if mod(k, 4) == 0
        lim = -ones(1, 3);                     % C: negative = no limit; MATLAB: nargin == 1
        I = ref_moment2current_fixed(m(:));
    else
        lim = 0.5 + rand(1, 3);
        I = ref_moment2current_fixed(m(:), lim(:));
    end
    in(k, :) = [m, lim];
    out(k, :) = I(:)';
end
comment(fid, 'moment2current3axis.m with mu_r defined. in: m(3) Imax(3) (negative = no limit). out: I(3)');
emit(fid, 'ML_M2C_IN', in);
emit(fid, 'ML_M2C_OUT', out);

%% ---------------- orbitalToECI.m ----------------
N = 30;
in = zeros(N, 6); out = zeros(N, 6);
for k = 1:N
    el = [6700 + 3000 * rand, 0.3 * rand, pi * rand, 2 * pi * rand, 2 * pi * rand, 2 * pi * rand];
    if k == 1, el = [7000, 0.01, 1.1, 0.3, 0.3, 0.7]; end
    [x, y, z, vx, vy, vz] = orbitalToECI(el(1), el(2), el(3), el(4), el(5), el(6));
    in(k, :) = el;
    out(k, :) = [x, y, z, vx, vy, vz];
end
comment(fid, 'orbitalToECI.m (km, rad). in: a e i RAAN argp nu. out: r(3) km, v(3) km/s');
emit(fid, 'ML_O2E_IN', in);
emit(fid, 'ML_O2E_OUT', out);

%% ---------------- eceftoeci.m ----------------
N = 25;
in = zeros(N, 4); out = zeros(N, 4);
for k = 1:N
    r = 6.4e6 * randn(1, 3) / 1.7;
    t = 946728000 + floor(rand * 1.0e9);
    if k == 1, r = [6.3761e6, -0.1387e6, 0.0807e6]; t = 1772814426; end
    re = eceftoeci(r(:), t);
    in(k, :) = [r, t];
    out(k, :) = [re(:)', ref_eceftoeci('jd_to_gmst', ref_eceftoeci('unix_to_jd', t))];
end
comment(fid, 'eceftoeci.m. in: r_ecef(3) m, unix. out: r_eci(3), GMST (deg)');
emit(fid, 'ML_E2E_IN', in);
emit(fid, 'ML_E2E_OUT', out);

%% ---------------- sunVectorECI.m ----------------
N = 30;
in = zeros(N, 1); out = zeros(N, 3);
for k = 1:N
    t = 946728000 + floor(rand * 1.0e9);
    [sx, sy, sz] = sunVectorECI(t / 86400 + 2440587.5); % the MATLAB takes a Julian date
    in(k) = t;
    out(k, :) = [sx, sy, sz];
end
comment(fid, 'sunVectorECI.m. in: unix time (converted to JD for MATLAB). out: sun(3)');
emit(fid, 'ML_SUN_IN', in);
emit(fid, 'ML_SUN_OUT', out);

%% ---------------- Two Body Propogation.m ----------------
N = 30;
in = zeros(N, 7); out = zeros(N, 6);
for k = 1:N
    el = [6.7e6 + 3e6 * rand, 0.5 * rand, 180 * rand, 360 * rand, 360 * rand, 360 * rand - 180, 6000 * rand];
    if k == 1, el = [(9600e3 + 21000e3) / 2, 0.37255, 0, 0, 0, 0, 10800]; end
    [a, e, i, raan, argp, nu] = propogateOrbitalElements(el(1), el(2), el(3), el(4), el(5), el(6), el(7));
    in(k, :) = el;
    out(k, :) = [a, e, i, raan, argp, nu];
end
comment(fid, 'propogateOrbitalElements (Two Body Propogation.m; m, deg, s). in: a e i RAAN argp nu dt. out: elements(6)');
emit(fid, 'ML_KEP_IN', in);
emit(fid, 'ML_KEP_OUT', out);

%% ---------------- magnetosphere.m ----------------
N = 25;
in = zeros(N, 5); out = zeros(N, 17);
[g0, h0, gd, hd] = ref_magnetosphere('loadWMM2025');
for k = 1:N
    d = randn(3, 1); d = d / norm(d);
    if k == 1, d = [0; 0.02; 1]; d = d / norm(d); end   % near the pole
    if k == 2, d = [1; 0; 0]; end                       % equator
    r = (6.8e6 + 4e5 * rand) * d;
    jd_int = 2460800 + floor(1000 * rand);
    jd_frac = rand;
    jd = jd_int + jd_frac;
    B_raw = ref_magnetosphere('wmmECI_embedded', r, jd);
    B_fix = ref_magnetosphere_fixed('wmmECI_embedded', r, jd);
    theta = ref_magnetosphere('gmst_from_jd', jd);
    Rz = [cos(theta) sin(theta) 0; -sin(theta) cos(theta) 0; 0 0 1];
    r_ecef = Rz * r;
    [lat, lon, alt] = ref_magnetosphere('ecef2geodetic', r_ecef);
    dy = ref_magnetosphere('jd2year', jd) - 2025.0;
    g = g0 + dy .* gd; h = h0 + dy .* hd;
    [bn, be, bd] = ref_magnetosphere('synthesizeMagField_manual', lat, lon, alt, g, h);
    [bn_f, be_f, bd_f] = ref_magnetosphere_fixed('synthesizeMagField_manual', lat, lon, alt, g, h);
    in(k, :) = [r', jd_int, jd_frac];
    out(k, :) = [B_raw', B_fix', ref_magnetosphere('jd2year', jd), theta, lat, lon, alt, ...
                 bn, be, bd, bn_f, be_f, bd_f];
end
comment(fid, ['magnetosphere.m (nT). in: r_eci(3) m, JD int, JD frac. out: B_raw(3) B_fixed(3) ', ...
              'decimal_year gmst(rad) lat lon alt NED_raw(3) NED_fixed(3)']);
emit(fid, 'ML_WMM_IN', in);
emit(fid, 'ML_WMM_OUT', out);

%% ---------------- pointing_error.m ----------------
N = 25;
in = zeros(N, 13); out = zeros(N, 7);
for k = 1:N
    rr = (6.8e6 + 4e5 * rand) * unit(randn(3, 1));
    vv = 7500 * unit(cross(rr, randn(3, 1)));
    target = 6.37e6 * unit(rr + 3e6 * randn(3, 1));
    qb = unit(randn(1, 4));
    if k == 1, qb = [1 0 0 0]; end
    clear pointing_error   % reset its persistent q_want_prev to [1 0 0 0]
    [q_tgtb, z_want] = pointing_error(rr, vv, qb, target);
    in(k, :) = [rr', vv', qb, target'];
    out(k, :) = [q_tgtb(:)', z_want(:)'];
end
comment(fid, 'pointing_error.m (fresh persistent state each case). in: r(3) v(3) q_b2eci(4) target(3). out: q_err(4) z_want(3)');
emit(fid, 'ML_POINT_IN', in);
emit(fid, 'ML_POINT_OUT', out);

%% ---------------- simulink.m UKF: building blocks ----------------
x = [0.01, -0.02, 0.03, 0.001, -0.002, 0.0005];
A = 0.1 * randn(6);
P = A * A' + 0.01 * eye(6);
lam = ref_simulink('calculate_lambda', 1, x);
[wc, wm] = ref_simulink('get_weights', lam, x, 1, 2);
sig = ref_simulink('get_sigma_points', lam, x, P);
fprintf(fid, '#define ML_UKF_LAMBDA %.17g\n', lam);
comment(fid, 'simulink.m get_weights (alpha = 1, beta = 2): row 1 = covariance weights, row 2 = mean weights');
emit(fid, 'ML_UKF_WEIGHTS', [wc; wm]);
comment(fid, 'simulink.m get_sigma_points(lam, x, P) for the x and P below: 13 x 6');
emit(fid, 'ML_UKF_SIGMA_X', x);
emit(fid, 'ML_UKF_SIGMA_P', P);
emit(fid, 'ML_UKF_SIGMAS', sig);

%% ---------------- simulink.m UKF: single steps from identical states ----------------
% Two configurations:
%   Q0 : Q = 0 and a small prior (0.6 deg). Here simulink.m (Q added after propagation, errors in
%        ECI frame) and the C filter (Q added before sigma points, errors in body frame) are the
%        same algorithm up to second-order terms, so they must agree tightly.
%   Q  : the simulink.m tuning (Q = 4e-6 per step) and a 3.6 deg prior, where the two ways of
%        adding Q legitimately differ.
configs = {'ML_UKF_STEPQ0', 0, 1e-4, 0.5; 'ML_UKF_STEP', 1, 0.004, 3};
fprintf(fid, '// UKF single steps: R = 2e-5 (mag), 1e-4 (second vector). num_vecs = 0 means predict only.\n');
for c = 1:size(configs, 1)
    [tag, q_scale, p_att, offset_deg] = configs{c, :};
    N = 24;
    in = zeros(N, 27);
    out = zeros(N, 4 + 3 + 36 + 3);
    Q = q_scale * diag([4e-6 * [1 1 1], 1e-10 * [1 1 1]]);
    P = diag([p_att * [1 1 1], 1e-6 * [1 1 1]]);
    for k = 1:N
        q_est = unit(randn(1, 4));
        q_true = quat_mul(q_est, rv2q(deg2rad(offset_deg) * unit(randn(1, 3))));
        bias = 0.002 * randn(1, 3);
        gyro = deg2rad(2) * randn(1, 3) + bias;
        ref = [unit(randn(1, 3)); unit(randn(1, 3))];
        nv = 2 - mod(k, 2);                               % alternate 2- and 1-vector updates
        if k > N - 4, nv = 0; end                         % a few predict-only steps
        dt = 0.1;
        body = zeros(1, 6);
        for j = 1:max(nv, 1)
            body(3 * j - 2:3 * j) = unit(rot(quat_conj(q_true), ref(j, :)) + 0.005 * randn(1, 3));
        end
        state = [0 0 0 bias + 1e-4 * randn(1, 3)];
        if nv == 2
            R = blkdiag(eye(3) * 2e-5, eye(3) * 1e-4); refs = ref; bm = body;
        else
            R = eye(3) * 2e-5; refs = ref(1, :); bm = body(1:3);
        end
        [ns, ng, nP] = ref_simulink('iterate', state, Quaternion(q_est), P, refs, bm, gyro, Q, R, dt, nv > 0);
        in(k, :) = [q_est, state, gyro, ref(1, :), ref(2, :), body, nv, dt];
        out(k, :) = [ng.to_array(), ns(4:6), reshape(nP', 1, 36), ns(1:3)];
    end
    comment(fid, sprintf('%s: P0 = diag(%g x3, 1e-6 x3), Q = %g * diag(4e-6 x3, 1e-10 x3), truth %g deg from the estimate', tag, p_att, q_scale, offset_deg));
    comment(fid, 'in: q_est(4) state(6) gyro(3) ref1(3) ref2(3) body(6) num_vecs dt. out: q_new(4) bias_new(3) P_new(36, row-major, GLOBAL-frame attitude errors about the pre-correction mean) x_hat(1:3) (q_new = rv2q(x_hat) * mean)');
    emit(fid, [tag '_IN'], in);
    emit(fid, [tag '_OUT'], out);
end
Q = diag([4e-6 * [1 1 1], 1e-10 * [1 1 1]]);

%% ---------------- simulink.m UKF: closed trajectory ----------------
dt = 0.1; N = 1200; update_every = 5; switch_step = 600;
q_true = unit([0.2812 -0.6998 0.5497 -0.3592]);
omega = deg2rad([2 0.5 -1]);
bias = [0.002 -0.001 0.0015];
mag0 = unit([0.3 -0.5 0.81]); sun0 = unit([0.9 0.4 -0.1]);
field_axis = unit([0.3 0.2 0.93]); field_rate = 4 * pi / 5400;
q_est0 = quat_mul(q_true, rv2q(deg2rad([6 -5 4])));
P0 = diag([0.01 * [1 1 1], 2.5e-5 * [1 1 1]]);
R2 = blkdiag(eye(3) * 2e-5, eye(3) * 1e-4); R1 = eye(3) * 2e-5;
fprintf(fid, '#define ML_TRAJ_DT %.17g\n#define ML_TRAJ_STEPS %d\n#define ML_TRAJ_UPDATE_EVERY %d\n#define ML_TRAJ_SWITCH_STEP %d\n', dt, N, update_every, switch_step);
comment(fid, 'Trajectory setup: q_true0(4) q_est0(4) P0 diag(6) Q diag(6) R2 diag(6) R1 diag(3) sun_ref(3)');
emit(fid, 'ML_TRAJ_SETUP', [q_true, q_est0, diag(P0)', diag(Q)', diag(R2)', diag(R1)', sun0]);
state = zeros(1, 6); guess = Quaternion(q_est0); cov = P0;
steps = zeros(N, 12);
checkpoints = zeros(N / 10, 1 + 4 + 3 + 4);
for k = 0:N - 1
    q_true = unit(quat_mul(q_true, rv2q(omega * dt)));
    gyro = omega + bias + 0.001 * randn(1, 3);
    mag_ref = rot(rv2q(field_axis * field_rate * dt * (k + 1)), mag0);
    do_update = mod(k, update_every) == 0;
    nv = ternary(k < switch_step, 2, 1);
    body = zeros(1, 6);
    if do_update
        body(1:3) = unit(rot(quat_conj(q_true), mag_ref) + 0.005 * randn(1, 3));
        if nv == 2
            body(4:6) = unit(rot(quat_conj(q_true), sun0) + 0.01 * randn(1, 3));
        end
    end
    if nv == 2
        refs = [mag_ref; sun0]; R = R2; bm = body;
    else
        refs = mag_ref; R = R1; bm = body(1:3);
    end
    [state, guess, cov] = ref_simulink('iterate', state, guess, cov, refs, bm, gyro, Q, R, dt, do_update);
    state(1:3) = 0;
    steps(k + 1, :) = [gyro, body, mag_ref];
    if mod(k + 1, 10) == 0
        checkpoints((k + 1) / 10, :) = [k, guess.to_array(), state(4:6), q_true];
    end
end
comment(fid, 'Per step k: gyro(3) body(6; zeros when no update) mag_ref(3). Updates when k % UPDATE_EVERY == 0; 2 vectors before SWITCH_STEP, magnetometer only after');
emit(fid, 'ML_TRAJ_STEP', steps, '%.9g');
comment(fid, 'Every 10 steps: k, MATLAB q_est(4), MATLAB bias(3), true q(4)');
emit(fid, 'ML_TRAJ_CHECK', checkpoints);

fprintf(fid, '#endif\n');
fclose(fid);
copyfile(tmp_out, out_file);
fprintf('wrote %s\n', out_file);
end

function restore(old_path, tmp)
path(old_path);
if isfolder(tmp)
    rmdir(tmp, 's');
end
end

%% ======================= helpers =======================
function ok = make_dispatcher(alg, file, tmp, name, fixes)
% Copy alg/file to tmp/name.m with a dispatcher prepended, applying exact text replacements.
txt = fileread(fullfile(alg, file));
ok = true;
for i = 1:size(fixes, 1)
    if contains(txt, fixes{i, 1})
        txt = strrep(txt, fixes{i, 1}, fixes{i, 2});
    else
        warning('fix not applied to %s (text not found, fixed upstream?): %s', file, fixes{i, 1});
        ok = false;
    end
end
if ~ok
    txt = fileread(fullfile(alg, file)); % all or nothing
end
disp_txt = sprintf('function varargout = %s(fname, varargin)\n[varargout{1:nargout}] = feval(fname, varargin{:});\nend\n\n', name);
if isempty(regexp(txt, '^\s*(%[^\n]*\n\s*)*function', 'once'))
    error('%s does not start with a function', file);
end
% A file like moment2current3axis.m has one function: call it by its own name through the dispatcher
first = regexp(txt, 'function\s+[^=]*=\s*(\w+)', 'tokens', 'once');
if ~isempty(first) && size(fixes, 1) > 0 && strcmp(file, 'moment2current3axis.m')
    disp_txt = sprintf('function varargout = %s(varargin)\n[varargout{1:nargout}] = %s(varargin{:});\nend\n\n', name, first{1});
end
fid = fopen(fullfile(tmp, [name '.m']), 'w');
fwrite(fid, [disp_txt txt]);
fclose(fid);
end

function extract_function(file, fname, last_statement, tmp)
lines = splitlines(fileread(file));
s = find(startsWith(strtrim(lines), 'function') & contains(lines, fname), 1);
l = find(contains(lines, last_statement), 1);
e = l - 1 + find(strcmp(strtrim(lines(l:end)), 'end'), 1);
assert(~isempty(s) && ~isempty(e), 'could not extract %s from %s', fname, file);
fid = fopen(fullfile(tmp, [fname '.m']), 'w');
fprintf(fid, '%s\n', lines{s:e});
fclose(fid);
end

function emit(fid, name, M, fmt)
if nargin < 4, fmt = '%.17g'; end
[r, c] = size(M);
fprintf(fid, 'static const double %s[%d][%d] = {\n', name, r, c);
for i = 1:r
    fprintf(fid, '    {%s},\n', strjoin(compose(fmt, M(i, :)), ', '));
end
fprintf(fid, '};\n#define %s_N %d\n\n', name, r);
end

function comment(fid, s)
fprintf(fid, '// %s\n', s);
end

function v = unit(v)
v = v / norm(v);
end

function r = ternary(c, a, b)
if c, r = a; else, r = b; end
end

% Plain Hamilton quaternion helpers for building test inputs (not under test)
function r = quat_mul(q, p)
r = [q(1)*p(1) - q(2)*p(2) - q(3)*p(3) - q(4)*p(4), ...
     q(1)*p(2) + q(2)*p(1) + q(3)*p(4) - q(4)*p(3), ...
     q(1)*p(3) - q(2)*p(4) + q(3)*p(1) + q(4)*p(2), ...
     q(1)*p(4) + q(2)*p(3) - q(3)*p(2) + q(4)*p(1)];
end

function r = quat_conj(q)
r = [q(1), -q(2), -q(3), -q(4)];
end

function q = rv2q(rv)
a = norm(rv);
if a < 1e-15, q = [1 0 0 0]; return; end
q = [cos(a / 2), sin(a / 2) * rv / a];
end

function w = rot(q, v)
p = quat_mul(quat_mul(q, [0, v(:)']), quat_conj(q));
w = p(2:4);
end
